Fix styling issues / Add condition to show Github's profile if email isn't public
eveningkid/gitfolio pull request #1
Opened 2018-04-03 19:15 UTC by vaporwavie

Hey @eveningkid! I've been working around this project of yours, gitfolio. 

This pull request fixes a few styling issues on SCSS. Some of the code on it was **deprecated**, so I fixed it. Also, **Github now hides the user's email if it isn't publicly configured** (I think it haves some _flag_ to enable it on the user dashboard). Well, that's basically it! Hope it helps. Great code of yours, man :smile:

2018-04-04 04:30 UTC, eveningkid commented on src/components/ReachMe.js
>                plus, I'm now <a href={mailtoAddress}>hireable</a>
Actually, we could do the same here:
```jsx
<span>
  {hireable ? "plus I'm now" : "I could soon be"} <a href={mailtoAdress}>hireable</a>
</span>
```

2018-04-04 04:30 UTC, eveningkid commented on src/components/ReachMe.js
> +        <a href={profile}>
```jsx
<a href={email === null ? profile : mailToAddress}>
```
This would be more concise! :)

2018-04-04 04:31 UTC, eveningkid requested changes
Thanks for the PR and your words (again). Please check my comments, I think it would make the code even more readable!

2018-04-04 23:06 UTC, vaporwavie commented
Okay! Gonna refactor with the code you suggested :)

2018-04-06 14:28 UTC, vaporwavie commented
@eveningkid I did the changes as requested :) https://github.com/eveningkid/gitfolio/pull/1/commits/2f528483edb1426e89af616fd54dc22320aefd69

2018-04-06 14:28 UTC, eveningkid approved these changes

2018-04-06 14:29 UTC, merged